name: Deploy Bot Function

on:
  workflow_dispatch:
  push:
    paths:
      - 'bot/**'
      - 'common/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy common folder
      run: |
        cp -r common bot/common

    - name: Install dependencies
      run: |
        cd bot
        npm install

    - name: Deploy to Lambda
      run: |
        cd bot
        zip -r function.zip .
        aws lambda update-function-code --function-name goaliphant-bot --zip-file fileb://function.zip

    - name: Clean up
      run: |
        rm -rf bot/common
