name: Deploy Bot Function

on:
  workflow_dispatch:
  push:
    paths:
      - 'goaliphant/bot/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 # Change to your region

    - name: Install dependencies
      run: |
        cd goaliphant/bot
        npm install

    - name: Deploy to Lambda
      run: |
        cd goaliphant/bot
        zip -r function.zip .
        aws lambda update-function-code --function-name goaliphant-bot --zip-file fileb://function.zip
